executor: slurm
jobs: unlimited
software-deployment-method: apptainer

default-resources:
  mem: 4G
  cpus: 1
  runtime: 20

slurm:
  sbatch-defaults:
    output: "logs/slurm/{rule}_{jobid}.out"
    error: "logs/slurm/{rule}_{jobid}.err"
