executor: slurm
jobs: unlimited
software-deployment-method: apptainer

default-resources:
  max_mem_mb_per_cpu: 5000
  runtime: 20

slurm:
  sbatch-defaults:
    output: "logs/slurm/{rule}_{jobid}.out"
    error: "logs/slurm/{rule}_{jobid}.err"
